version: '3'

services:
  iwestfs:
    image: iwestfs
    entrypoint: /bin/bash
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./model:/app/model
      - ./config:/app/config
    environment:
      - QT_X11_NO_MITSHM=1
      - DISPLAY=:0
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    network_mode: host

