version: '3'

services:
  iwestfs:
    image: iwestfs-ljj
    entrypoint: /bin/bash
    tty: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY
      - DISPLAY=:0
      - XDG_RUNTIME_DIR
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    network_mode: host

