# FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-devel
FROM nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04
RUN apt-get update 
RUN apt install --no-install-recommends -y gcc git zip curl htop libgl1-mesa-glx libglib2.0-0 libpython3-dev gnupg g++
RUN apt-get update && apt-get install -y \
    libx11-dev \
    libgl1-mesa-glx 

# # RUN apt install -y python3.8

# # RUN apt install -y pip



WORKDIR /app
RUN git clone https://github.com/snuailab-biz/iwest-fs.git .
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile=default
RUN export PATH="$HOME/.cargo/bin:$PATH"

RUN apt install -y python3 pip
RUN pip install -U pip setuptools 

RUN pip install torch torchvision
RUN pip install opencv-python matplotlib pyyaml
# RUN pip install transformers==4.11.3
# RUN pip install -r requirements.txt

# RUN cd iwestfs/models/ops
# RUN python3 setup.py build install
# RUN cd ../../..

# # ENV DISPLAY=:0


# RUN git pull
# RUN git pull
# CMD ["python3", "exe.py"]