model_name: mdef_detr
pretrained_model: model/MDef_DETR_r101_epoch20_ore.pth
batch_size: 3
image_show: true
restapi_url: http://0.0.0.0:8080/dkserver
device: cuda:0

cam: 
  - url: rtsp://admin:!1q2w3e4r@192.168.3.96:554/profile1/media.smp
    color: RGB
    rois: 
      - x1: 420
        y1: 0
        x2: 1500
        y2: 1080
        name: 28
        caption: Fire and Smoke
        event: flame_snuai
  # - url: 0
  #   color: RGB
  #   rois: 
  #     - x1: 0
  #       y1: 0
  #       x2: 0
  #       y2: 0
  #       name: 28
  #       caption: Fire and Smoke",
  #       event: flame1
  #     - x1: 0
  #       y1: 0
  #       x2: 0
  #       y2: 0
  #       name: 28
  #       caption: nose of human
  #       event: nose_of_human
